#!/bin/bash
JSON_FILE=$REMOTE_SSH_CONFIG_PATH

if ! [ -x "$(command -v jq)" ]; then
  echo 'Error: jq is not installed.' >&2
  exit 1
fi

if ! [ -f "$JSON_FILE" ]; then
  echo "Error: File '$JSON_FILE' does not exist." >&2
  exit 1
fi

DATA=$(cat $JSON_FILE)

export SSH_SERVER=$(echo $DATA | jq -r '.server')
export SSH_PORT=$(echo $DATA | jq -r '.port')
export SSH_USERNAME=$(echo $DATA | jq -r '.username')
export SSH_KEY_PATH=$(echo $DATA | jq -r '.keyPath')

ssh -o TCPKeepAlive=yes -o ServerAliveCountMax=20 -o ServerAliveInterval=15 -q -L 3000:localhost:3000 -l $SSH_USERNAME -p $SSH_PORT -i $SSH_KEY_PATH $SSH_SERVER
