#!/bin/bash
set -e

BASE_URL="https://raw.githubusercontent.com/sobanieca/env-setup/master/"

echo "Updating update-configs tool"
wget $BASE_URL"update-configs" -O $HOME/tools/update-configs
chmod +x $HOME/tools/update-configs
echo "update-configs tool updated"

if [ ! -d "$HOME/.config" ]; then
    echo "Creating .config directory..."
    mkdir $HOME/.config
    echo ".config directory created."
fi

if [ ! -d "$HOME/.config/nvim" ]; then
    echo "Creating .config/nvim directory..."
    mkdir $HOME/.config/nvim
    echo ".config/nvim directory created."
fi

echo "Updating .bashrcx file..."
wget $BASE_URL"bashrcx" -O $HOME/.bashrcx
echo ".bashrcx file updated."

echo "Updating tmux.conf file..."
wget $BASE_URL"tmux.conf" -O $HOME/.tmux.conf
echo "tmux.conf file replaced."

echo "Updating gitmux.conf file..."
wget $BASE_URL"gitmux.conf" -O $HOME/.config/.gitmux.conf
echo "gitmux.conf file replaced."

echo "Updating nvim/init.lua..."
wget $BASE_URL"nvim-init.lua" -O $HOME/.config/nvim/init.lua
echo "nvim/init.lua updated."

echo "Updating nvim/legacy.vim..."
wget $BASE_URL"nvim-legacy.vim" -O $HOME/.config/nvim/legacy.vim
echo "nvim/legacy.vim updated."

echo "Updating coc-settings.json..."
wget $BASE_URL"coc-settings.json" -O $HOME/.config/nvim/coc-settings.json
echo "coc-settings json updated"

echo "Updating ports tool"
wget $BASE_URL"ports" -O $HOME/tools/ports
chmod +x $HOME/tools/ports
echo "ports tool updated"

echo "Updating sniff tool"
wget $BASE_URL"sniff" -O $HOME/tools/sniff
chmod +x $HOME/tools/sniff
echo "sniff tool updated"

echo "Updating remote tool"
wget $BASE_URL"remote" -O $HOME/tools/remote
chmod +x $HOME/tools/remote
echo "remote tool updated"

echo "Updating debinfo tool"
wget $BASE_URL"debinfo" -O $HOME/tools/debinfo
chmod +x $HOME/tools/debinfo
echo "debinfo tool updated"

echo "Updating gshow tool"
wget $BASE_URL"gshow" -O $HOME/tools/gshow
chmod +x $HOME/tools/gshow
echo "gshow tool updated"

echo "Updating gblame tool"
wget $BASE_URL"gblame" -O $HOME/tools/gblame
chmod +x $HOME/tools/gblame
echo "gblame tool updated"

echo "Updating rm-nvim-bookmarks tool"
wget $BASE_URL"rm-nvim-bookmarks" -O $HOME/tools/rm-nvim-bookmarks
chmod +x $HOME/tools/rm-nvim-bookmarks
echo "rm-nvim-bookmarks tool updated"

echo "Updating aid tool"
wget $BASE_URL"aid" -O $HOME/tools/aid
chmod +x $HOME/tools/aid
echo "aid tool updated"

